import type { Locale } from './locales';

const media = {
  heroVideo: '/media/about/hero-video.mp4',
  heroPoster: '/media/about/festival-closing.jpg',
  what: '/media/about/what-contact.jpg',
  why: ['/media/about/why-01.jpg', '/media/about/why-02.jpg', '/media/about/why-03.jpg', '/media/about/festival-encounter.jpg', '/media/about/performance-lab.jpg'],
  who: ['/media/about/festival-flow.jpg', '/media/about/DSC03637.jpg'],
  city: '/media/about/movement-outside.jpg',
  organisers: '/media/about/Org-2.jpg',
  closing: '/media/about/performance-1.jpg',
};

export const aboutCopy: Record<Locale, any> = {
  en: {
    title: 'About Contact+', strapline: 'Movement · Contact Improvisation · Performance',
    lead: 'An international festival of Contact Improvisation, performance and shared practice in Chișinău.',
    date: '26 September — 4 October 2026', place: 'Chișinău, Moldova',
    what: { title: 'What is Contact+', text: 'Contact+ brings together Contact Improvisation, movement practice, performance and the living social space around them. It is more than a sequence of classes or shows: people arrive, practise, watch, talk, dance and make time together.' },
    why: { title: 'Why people come', items: ['To deepen a movement or Contact Improvisation practice.', 'To explore where CI meets performance and composition.', 'To take part in laboratories, performances, JAMs and gatherings.', 'To meet an international movement community in Chișinău.'] },
    unfold: { title: 'How Contact+ unfolds', text: 'The festival has many points of entry, but no single way to move through it.', structureTitle: 'Five program lines', structureText: 'Contact+ brings together five connected program lines. You can enter through practice, performance research, family and youth formats, public performances, or the shared life of the festival.', dimensions: ['Contact Improvisation', 'Performance Labs', 'Family & Youth Program', 'Performances', 'Jams & Festival Life'], dimensionText: ['Classes, intensives and embodied research.', 'Research, composition and shared investigation.', 'Movement spaces for families and younger participants.', 'Works, showings and encounters with an audience.', 'JAMs, conversations and the life around the program.'] },
    day: { title: 'A day at Contact+', note: 'This is a possible festival rhythm, not a timetable repeated every day.', phaseTimes: ['Morning', 'Afternoon', 'Evening'], phaseTitles: ['Start with practice', 'Move into exchange', 'Stay for the evening'], phaseTexts: ['Begin slowly, arrive in the body and tune in to the people around you.', 'Practice, rest, conversation and performance research meet.', 'Let the day open into watching, participating and shared festival life.'], items: ['Morning practice', 'CI intensive or class', 'Lunch, rest and conversations', 'Performance lab', 'Performance or showing', 'JAM or evening gathering'] },
    who: { title: 'Who gathers here', intro: 'Contact+ is open to people with different backgrounds, from those simply curious about moving together to experienced practitioners.', gathering: 'Who gathers here', groups: ['People curious about movement practice', 'Families and young movers', 'Local performance audiences', 'Dancers and performers', 'Movement teachers and artists', 'Contact Improvisation practitioners'], entry: 'Finding your entry point', entryText: 'Some formats offer an entry point for people newer to Contact Improvisation. Other intensives and performance laboratories may assume previous movement, CI or performance experience. Individual event pages remain the place for specific participation guidance.' },
    city: { label: 'Local context', title: 'Rooted in Chișinău', text: 'Contact+ grows from a local movement and performance context while welcoming artists and teachers from elsewhere. The city becomes part of the festival rhythm: studios, walks, conversations and evenings shape the week together.' },
    video: { heroLabel: 'Moving through a Contact+ practice space', vimeoLabel: 'Watch festival film', filmLabel: 'Contact+ in motion', filmText: 'A glimpse of the people, movement and shared attention that shape Contact+.' },
    organisers: { title: 'Who makes Contact+ possible', intro: 'Contact+ is held by local artists, organisers and community partners who shape the practical and artistic life of the festival.', coreGroup: 'Festival direction & organisation', partnersGroup: 'Community partners', supportGroup: 'Music & participant support', dance: 'festival directors; dancers, performers, choreographers and teachers', manager: 'manager', musician: 'instrumentalist and musician', support: 'communication and administrative support for participants', festivalTeam: 'Team of Moldova Dance Festival Contact+', community: 'Contact Improvisation Community of Moldova' },
    participation: { title: 'Participation', text: 'Choose the formats that fit your experience and interests, then register through the festival form.', passes: 'Passes & Participation →', register: 'Register for Contact+ →' },
    faqTitle: 'Questions', faq: [
      ['Do I need previous Contact Improvisation experience?', 'Some formats welcome people newer to CI; others assume previous movement, CI or performance experience. Check individual event pages before choosing.'],
      ['Is Contact+ only for dancers?', 'No. Contact+ is also open to beginners and people who are simply curious about movement. Some formats are made as entry points, while others are better for people with previous CI, movement or performance experience.'],
      ['How do I choose a participation format?', 'Start with the program lines, then read individual event pages for format and participation guidance.'],
      ['How do I register?', 'Use the festival registration form:']
    ],
    explore: { title: 'Explore the festival', program: 'Explore the program →', schedule: 'View the schedule →', artists: 'Meet the artists →' },
  },
  ro: {
    title: 'Despre Contact+', strapline: 'Mișcare · Improvizație de contact · Performance',
    lead: 'Un festival internațional de Improvizație de contact, performance și practică împărtășită la Chișinău.',
    date: '26 septembrie — 4 octombrie 2026', place: 'Chișinău, Moldova',
    what: { title: 'Ce este Contact+?', text: 'Contact+ aduce împreună Improvizația de contact, practica mișcării, performance-ul și spațiul social viu din jurul lor. Este mai mult decât o succesiune de clase sau spectacole: oamenii sosesc, practică, privesc, vorbesc, dansează și își fac timp unii pentru alții.' },
    why: { title: 'De ce vin oamenii', items: ['Pentru a aprofunda practica mișcării sau a Improvizației de contact.', 'Pentru a explora întâlnirea dintre CI, performance și compoziție.', 'Pentru a participa la laboratoare, performance-uri, JAM-uri și întâlniri.', 'Pentru a întâlni o comunitate internațională de mișcare în Chișinău.'] },
    unfold: { title: 'Cum se desfășoară Contact+', text: 'Festivalul are mai multe puncte de intrare, dar nu un singur mod de a-l parcurge.', structureTitle: 'Cinci linii de program', structureText: 'Contact+ reunește cinci linii de program conectate. Poți intra prin practică, cercetare performativă, formate pentru familii și tineri, performance-uri publice sau prin viața împărtășită a festivalului.', dimensions: ['Improvizație de contact', 'Laboratoare de performance', 'Program pentru familii și tineri', 'Performance-uri', 'JAM-uri și viața festivalului'], dimensionText: ['Clase, intensive și cercetare prin corp.', 'Cercetare, compoziție și explorare împărtășită.', 'Spații de mișcare pentru familii și participanți mai tineri.', 'Lucrări, showing-uri și întâlniri cu publicul.', 'JAM-uri, conversații și viața din jurul programului.'] },
    day: { title: 'O zi la Contact+', note: 'Acesta este un posibil ritm al festivalului, nu un orar repetat în fiecare zi.', phaseTimes: ['Dimineața', 'După-amiaza', 'Seara'], phaseTitles: ['Începe cu practica', 'Intră în schimb', 'Rămâi pentru seară'], phaseTexts: ['Începe încet, ajungi în corp și intri în relație cu oamenii din jur.', 'Practica, odihna, conversația și cercetarea performativă se întâlnesc.', 'Lași ziua să se deschidă către privire, participare și viața festivalului.'], items: ['Practica de dimineață', 'Intensiv sau clasă de CI', 'Prânz, odihnă și conversații', 'Laborator de performance', 'Performance sau showing', 'JAM sau întâlnire de seară'] },
    who: { title: 'Cine se adună aici', intro: 'Contact+ este deschis oamenilor cu experiențe diferite, de la cei pur și simplu curioși să se miște împreună la practicanți cu experiență.', gathering: 'Cine se adună aici', groups: ['Persoane curioase de practica mișcării', 'Familii și tineri în mișcare', 'Public local de performance', 'Dansatori și performeri', 'Profesori de mișcare și artiști', 'Practicanți de Improvizație de contact'], entry: 'Găsește-ți punctul de intrare', entryText: 'Unele formate oferă un punct de intrare pentru persoane mai noi în CI. Alte intensive și laboratoare de performance pot presupune experiență anterioară de mișcare, CI sau performance. Paginile fiecărui eveniment rămân sursa pentru indicații specifice de participare.' },
    city: { label: 'Context local', title: 'Înrădăcinat în Chișinău', text: 'Contact+ crește dintr-un context local de mișcare și performance, primind în același timp artiști și profesori din alte locuri. Orașul devine parte din ritmul festivalului: studiouri, plimbări, conversații și seri modelează împreună săptămâna.' },
    video: { heroLabel: 'Mișcare într-un spațiu de practică Contact+', vimeoLabel: 'Privește filmul festivalului', filmLabel: 'Contact+ în mișcare', filmText: 'O privire asupra oamenilor, mișcării și atenției împărtășite care dau formă Contact+.' },
    organisers: { title: 'Cine face Contact+ posibil', intro: 'Contact+ este susținut de artiști locali, organizatori și parteneri comunitari care modelează viața practică și artistică a festivalului.', coreGroup: 'Direcție și organizare', partnersGroup: 'Parteneri comunitari', supportGroup: 'Muzică și sprijin pentru participanți', dance: 'directori de festival; dansatori, performeri, coregrafi și profesori', manager: 'manager', musician: 'instrumentist și muzician', support: 'sprijin de comunicare și administrativ pentru participanți', festivalTeam: 'Echipa Moldova Dance Festival Contact+', community: 'Comunitatea de Improvizație de contact din Moldova' },
    participation: { title: 'Participare', text: 'Alege formatele potrivite experienței și intereselor tale, apoi înregistrează-te prin formularul festivalului.', passes: 'Abonamente și participare →', register: 'Înregistrează-te la Contact+ →' },
    faqTitle: 'Întrebări', faq: [
      ['Am nevoie de experiență anterioară în Improvizație de contact?', 'Unele formate primesc persoane noi în CI; altele presupun experiență anterioară de mișcare, CI sau performance. Verifică pagina fiecărui eveniment înainte de alegere.'],
      ['Contact+ este doar pentru dansatori?', 'Nu. Contact+ este deschis și începătorilor și persoanelor pur și simplu curioase de mișcare. Unele formate sunt puncte de intrare, iar altele sunt mai potrivite pentru persoane cu experiență anterioară în CI, mișcare sau performance.'],
      ['Cum aleg un format de participare?', 'Începe cu liniile de program, apoi citește paginile fiecărui eveniment pentru format și indicații de participare.'],
      ['Cum mă înregistrez?', 'Folosește formularul de înregistrare al festivalului:']
    ],
    explore: { title: 'Explorează festivalul', program: 'Explorează programul →', schedule: 'Vezi orarul →', artists: 'Cunoaște artiștii →' },
  },
  ru: {
    title: 'О фестивале Contact+', strapline: 'Движение · Контактная импровизация · Перформанс',
    lead: 'Международный фестиваль Контактной импровизации, перформанса и совместной практики в Кишинёве.',
    date: '26 сентября — 4 октября 2026', place: 'Кишинёв, Молдова',
    what: { title: 'Что такое Contact+?', text: 'Contact+ объединяет Контактную импровизацию, практики движения, перформанс и живое социальное пространство вокруг них. Это больше, чем череда классов или показов: люди приезжают, практикуют, смотрят, разговаривают, танцуют и проводят время вместе.' },
    why: { title: 'Зачем приезжают', items: ['Углубить практику движения или Контактной импровизации.', 'Исследовать встречу CI, перформанса и композиции.', 'Участвовать в лабораториях, перформансах, JAM и встречах.', 'Встретить международное сообщество движения в Кишинёве.'] },
    unfold: { title: 'Как разворачивается Contact+', text: 'У фестиваля несколько точек входа, но нет единственного способа пройти его от начала до конца.', structureTitle: 'Пять линий программы', structureText: 'Contact+ объединяет пять связанных линий программы. Можно начать с практики, перформативного исследования, форматов для семей и молодёжи, публичных перформансов или с общей жизни фестиваля.', dimensions: ['Контактная импровизация', 'Перформанс-лаборатории', 'Программа для семей и молодёжи', 'Перформансы', 'JAM и фестивальная жизнь'], dimensionText: ['Классы, интенсивы и исследование через тело.', 'Исследование, композиция и совместный поиск.', 'Пространства движения для семей и молодых участников.', 'Работы, показы и встречи со зрителями.', 'JAM, разговоры и жизнь вокруг программы.'] },
    day: { title: 'Один день на Contact+', note: 'Это возможный ритм фестиваля, а не расписание, повторяющееся каждый день.', phaseTimes: ['Утро', 'День', 'Вечер'], phaseTitles: ['Начать с практики', 'Перейти к обмену', 'Остаться на вечер'], phaseTexts: ['Начать медленно, прийти в тело и настроиться на людей вокруг.', 'Практика, отдых, разговор и перформативное исследование встречаются.', 'Позволить дню открыться просмотру, участию и общей жизни фестиваля.'], items: ['Утренняя практика', 'CI-интенсив или класс', 'Обед, отдых и разговоры', 'Перформанс-лаборатория', 'Перформанс или показ', 'JAM или вечерняя встреча'] },
    who: { title: 'Кто собирается здесь', intro: 'Contact+ открыт людям с разным опытом: от тех, кому просто интересно двигаться вместе, до практикующих с большим стажем.', gathering: 'Кто собирается здесь', groups: ['Люди, которым интересна практика движения', 'Семьи и молодые люди в движении', 'Местная аудитория перформанса', 'Танцовщики и перформеры', 'Преподаватели движения и художники', 'Практикующие Контактную импровизацию'], entry: 'Найдите свою точку входа', entryText: 'Некоторые форматы подходят людям, недавно пришедшим в CI. Другие интенсивы и перформанс-лаборатории могут предполагать предыдущий опыт движения, CI или перформанса. Точные рекомендации по участию указаны на страницах отдельных событий.' },
    city: { label: 'Местный контекст', title: 'Укоренён в Кишинёве', text: 'Contact+ вырастает из местного контекста движения и перформанса и одновременно приглашает художников и преподавателей из других стран. Город становится частью ритма фестиваля: студии, прогулки, разговоры и вечера вместе формируют эту неделю.' },
    video: { heroLabel: 'Движение в пространстве практики Contact+', vimeoLabel: 'Смотреть фильм фестиваля', filmLabel: 'Contact+ в движении', filmText: 'Взгляд на людей, движение и общее внимание, которые формируют Contact+.' },
    organisers: { title: 'Кто делает Contact+ возможным', intro: 'Contact+ держится на местных художниках, организаторах и партнёрах сообщества, которые формируют практическую и художественную жизнь фестиваля.', coreGroup: 'Дирекция и организация', partnersGroup: 'Партнёры сообщества', supportGroup: 'Музыка и поддержка участников', dance: 'директора фестиваля; танцовщики, перформеры, хореографы и преподаватели', manager: 'менеджер', musician: 'инструменталист и музыкант', support: 'коммуникационная и административная поддержка участников', festivalTeam: 'Команда Moldova Dance Festival Contact+', community: 'Сообщество Контактной импровизации Молдовы' },
    participation: { title: 'Участие', text: 'Выберите форматы, подходящие вашему опыту и интересам, затем зарегистрируйтесь через форму фестиваля.', passes: 'Абонементы и участие →', register: 'Зарегистрироваться на Contact+ →' },
    faqTitle: 'Вопросы', faq: [
      ['Нужен ли опыт Контактной импровизации?', 'Некоторые форматы подходят людям, недавно пришедшим в CI; другие предполагают опыт движения, CI или перформанса. Перед выбором проверьте страницу отдельного события.'],
      ['Contact+ — только для танцовщиков?', 'Нет. Contact+ открыт и для новичков, и для людей, которым просто интересно движение. Некоторые форматы задуманы как точки входа, другие больше подходят участникам с опытом CI, движения или перформанса.'],
      ['Как выбрать формат участия?', 'Начните с линий программы, затем прочитайте страницы отдельных событий: там есть описание формата и рекомендации по участию.'],
      ['Как зарегистрироваться?', 'Воспользуйтесь регистрационной формой фестиваля:']
    ],
    explore: { title: 'Исследуйте фестиваль', program: 'Посмотреть программу →', schedule: 'Открыть расписание →', artists: 'Познакомиться с артистами →' },
  },
};

export const aboutMedia = media;
