import type { Locale } from './locales';

const shared = {
  registrationUrl: 'https://docs.google.com/forms/d/e/1FAIpQLSdkDT1NjKXxzbAg_8dqSLEDnYPstOaBZ8oE6mxqNHkLTUbBlg/viewform?usp=header',
  eventSlugs: {
    opening: ['shared-awareness', 'arriving-into-the-touch'],
    openingIncluded: ['first-meetings-jam', 'welcoming-open-circle-jam', 'the-wild-one'],
    ciMain: ['ci-as-artsport', 'dynamic-flying'],
    ciSecond: ['risk-play-flight'],
    labsMain: ['choice-as-bodily-experience', 'touching-stories'],
    labsSecond: ['seeing-and-being-seen'],
    jams: ['first-meetings-jam', 'welcoming-open-circle-jam', 'jam', 'jam', 'celebration-jam', 'farewell-jam'],
    family: ['little-curiosity-family-baby-6', 'little-curiosity-family-kids-6', 'the-wild-one', 'family-time-discussion', 'youth-dance-class'],
  },
};

export const passesShared = shared;

export const passesCopy: Record<Locale, any> = {
  en: {
    title: 'Passes & Participation',
    strapline: 'Movement · Contact Improvisation · Performance',
    lead: 'Choose how you want to take part in Contact+.',
    heroText: 'Join the complete nine-day festival, follow a focused path through Contact Improvisation or performance, enter through the opening weekend, or take part through JAMs and the Family & Youth Program.',
    date: '26 September — 4 October 2026', place: 'Chișinău, Moldova',
    actions: { register: 'Register for Contact+', program: 'Explore the program', schedule: 'View the schedule', soon: 'Available soon' },
    pricing: { regular: 'Regular', late: 'Late', regularNote: 'Until 1 September', lateNote: 'After 1 September', intro: 'Regular prices are available until 1 September 2026. Late prices apply after 1 September 2026.', label: 'Regular and late prices', currency: 'All prices are in euros' },
    how: {
      title: 'How participation works',
      paragraphs: ['Contact+ can be entered in different ways.', 'The Full Festival Pass gives the broadest access. You can also choose a focused path through the opening weekend, Contact Improvisation, Performance Labs, JAMs or the Family & Youth Program.', 'Some formats run in parallel. Where two intensives or laboratories take place at the same time, participants choose one. Some additional formats can be added at a reduced combined price.'],
      steps: ['Choose the Full Festival Pass or your main path.', 'Extend it with a compatible intensive, laboratory or selected JAMs.', 'Join selected formats individually where available.', 'Buy separate performance tickets through the festival ticket platform when sales open.'],
    },
    full: {
      title: 'Full Festival Pass', kicker: 'The complete festival rhythm',
      text: 'For participants who want to enter the complete rhythm of Contact+. The pass gives access to the full festival program across practice, performance and shared festival life, within the possibilities of the schedule.',
      includesTitle: 'Included in the Full Festival Pass',
      includes: ['All Contact Improvisation intensives', 'All Performance Labs', 'All JAMs', 'Showings and performances', 'Gatherings and shared festival events', 'Family & Youth Program formats when the participant matches the age and participation frame', 'Family Time & Discussion'],
      parallel: 'Some events run in parallel. In these cases, Full Festival Pass holders choose which event to attend.',
      performances: 'A dedicated section of each performance venue is reserved for Full Festival Pass holders, so individual performances do not need to be selected in advance.',
      family: 'A pass holder may attend an appropriate Family & Youth event with their child without a separate Family Pass. The registration form should still include the child’s information for capacity and organisation.',
      noteLabels: ['Parallel events', 'Performances', 'Family participation'],
      cta: 'Register for the Full Festival Pass',
    },
    paths: {
      title: 'Choose how you want to join',
      text: 'Choose one main participation path. Compatible JAMs and additional formats can be added during registration.',
      items: [
        ['full-festival', 'Full Festival Pass', '9 days · €450 Regular', 'For the complete festival rhythm'],
        ['opening', 'Opening Weekend', '2 days · €120 Regular', 'For a clear first entry into Contact+'],
        ['ci', 'Contact Improvisation', '3–5 days · from €100 Regular', 'For an intensive movement practice'],
        ['labs', 'Performance Labs', '3–6 days · from €130 Regular', 'For a focused performance process'],
        ['family', 'Family & Youth Program', '1–2 days · from €40 Regular', 'For children, families and young adults'],
        ['jams', 'JAM Access', 'Individual dates · from €10 Regular', 'For flexible participation'],
      ],
    },
    opening: {
      title: 'Opening Weekend Pass', text: 'Begin Contact+ through two connected days of practice and the festival’s opening events.',
      choose: 'Choose exactly one of two parallel two-day formats:', meta: '2-day intensive',
      after: 'Then join First Meetings JAM, Welcoming Open Circle & JAM and The Wild One. The Wild One is available to Opening Weekend participants who wish to attend it.',
      unavailable: 'Shared Awareness and Arriving into the Touch are available through this pass and are not currently sold separately.',
      cta: 'Choose your opening format',
      packageTitle: 'Your Opening Weekend Pass includes',
      chooseTitle: 'Choose one intensive',
      includedTitle: 'Included with either choice',
      includedText: 'Your Opening Weekend Pass includes one of the two parallel intensives above plus all three events below.',
      selectionNote: 'Indicate your chosen intensive in the registration form.',
    },
    ci: {
      title: 'Contact Improvisation', intro: 'Choose a three-day CI intensive, continue with Risk, Play & Flight, or combine both parts into a longer practice path.',
      mainTitle: 'Main three-day intensive', choose: 'Choose one of two parallel formats:', mainMeta: 'CI intensive · 3 days',
      secondTitle: 'Risk, Play & Flight', secondMeta: 'CI intensive · 2 days',
      secondText: 'This intensive takes place separately. It can be purchased independently or added to either main CI intensive.',
      separate: 'Separate price', combined: 'Price as the second CI format', discount: 'The reduced price applies to Risk, Play & Flight as the second format.',
      total: 'Combined total', regularTotal: '€245 Regular', lateTotal: '€325 Late',
      excluded: 'Morning practices, discussions, other shared events and JAMs are not automatically included. JAMs can be added separately.',
      ctas: ['Choose a CI intensive', 'Add Risk, Play & Flight', 'Add JAMs'],
      builderTitle: 'Choose one of three ways to participate',
      builderText: 'Choose the format that fits the amount of practice you want.',
      optionTitles: ['3-day intensive', 'Risk, Play & Flight', 'Both — 5-day path'],
      optionMeta: ['3 days · choose one parallel intensive', '2 days · independent intensive', '5 days · main intensive + Risk, Play & Flight'],
      optionNotes: ['Choose CI as ArtSport or Dynamic Flying.', 'Join Risk, Play & Flight without a main intensive.', 'Choose one main intensive and continue with Risk, Play & Flight.'],
      register: 'Register for Contact Improvisation',
      formNote: 'You will indicate the participation option and intensive in the registration form.',
    },
    labs: {
      title: 'Performance Labs', intro: 'Choose one three-day laboratory, add Seeing and being seen, or follow both parts as a longer performance path.',
      mainTitle: 'Main laboratory', choose: 'Choose one of two parallel three-day formats:', mainMeta: 'Performance laboratory · 3 days',
      secondTitle: 'Seeing and being seen', secondMeta: 'Performance lab · 3-day laboratory',
      secondText: 'This laboratory takes place separately. It can be purchased independently or added to either main Performance Lab.',
      separate: 'Separate price', combined: 'Price as the second laboratory', discount: 'The reduced price applies to Seeing and being seen as the second laboratory.',
      total: 'Combined total', regularTotal: '€295 Regular', lateTotal: '€380 Late',
      note: 'All related laboratory showings are accessible with any Performance Lab participation option. No motivation letter, application selection or teacher approval is currently required. JAMs can be added separately.',
      ctas: ['Choose a Performance Lab', 'Add Seeing and being seen', 'Add JAMs'],
      builderTitle: 'Choose one of three ways to participate',
      builderText: 'Choose the format that fits the amount of practice you want.',
      optionTitles: ['3-day Performance Lab', 'Seeing and being seen', 'Both — 6-day path'],
      optionMeta: ['3 days · choose one parallel laboratory', '3 days · independent laboratory', '6 days · main laboratory + Seeing and being seen'],
      optionNotes: ['Choose Choice as Bodily Experience or Touching Stories.', 'Join Seeing and being seen without a main laboratory.', 'Choose one main laboratory and continue with Seeing and being seen.'],
      register: 'Register for Performance Labs',
      formNote: 'You will indicate the participation option and laboratory in the registration form.',
    },
    jams: {
      title: 'JAM Access', intro: 'Choose individual JAMs or create a longer JAM path through the festival. During registration, indicate which JAMs you plan to attend.',
      events: ['JAM — 26 September', 'JAM — 27 September', 'JAM — 28 September', 'JAM — 29 September', 'JAM — 3 October', 'JAM — 4 October'],
      generalTitle: 'JAM-only pricing', generalNote: 'For visitors not purchasing a CI intensive or Performance Lab.',
      participantTitle: 'Participant add-on pricing', participantNote: 'For someone purchasing a CI intensive or Performance Lab. Extend your practice into the JAMs and stay connected to the shared festival rhythm.',
      single: 'Single JAM', three: 'Three or more', perJam: 'per JAM', one: '1 JAM', all: 'All 6 JAMs',
      capacity: 'Advance registration and payment are preferred. Entry and payment on the door are possible only when capacity remains.',
      choiceTitle: 'Which JAM price applies to you?',
      generalChoice: 'JAMs only',
      participantChoice: 'CI or Performance Lab + JAMs',
    },
    family: {
      title: 'Family & Youth Program', intro: 'Choose family participation or the complete two-day Youth Dance Class.',
      passTitle: 'Family Pass', includedTitle: 'Included formats', includes: 'One Family Pass includes one child and one accompanying adult, one age-appropriate Little Curiosity class, The Wild One and Family Time & Discussion.',
      age: 'Choose Little Curiosity by the child’s age: under 6 on day 1, 6+ on day 2. The accompanying adult takes part in The Wild One.',
      additional: 'Additional child or adult from the same family', additionalText: 'Add one child or adult from the same family at the reduced price below.',
      wild: 'The Wild One will also be sold separately as a performance ticket.',
      youthTitle: 'Youth Dance Class', youthMeta: 'Complete 2-day format', youthText: 'A two-day movement format created primarily for teenagers and young adults. It is sold only as the complete two-day format.',
      productsTitle: 'Choose one participation product',
      additionalLabel: 'Optional Family Pass add-on',
    },
    performances: { title: 'Performances', text: 'Performance tickets are also available separately through the festival ticket platform. Full Festival Pass holders access the performance program through a reserved festival section. The Opening Weekend Pass includes The Wild One.', cta: 'Explore performance tickets' },
    registration: {
      title: 'How registration works',
      steps: [['Choose your path', 'Select the Full Festival Pass, a focused program path, Family & Youth participation or selected JAMs.'], ['Complete the registration form', 'Indicate the formats and JAMs you want to attend.'], ['Receive confirmation', 'The festival team confirms availability and sends payment instructions.'], ['Complete payment', 'A place is secured after payment is confirmed.'], ['Receive practical information', 'Final organisational information is sent before the festival.']],
    },
    practical: {
      title: 'Practical conditions',
      groupTitles: ['Participation and capacity', 'Registration and prices', 'Individual support', 'Cancellations'],
      items: [['Capacity', 'Places in intensives, laboratories, JAMs and Family & Youth formats may be limited.'], ['Parallel formats', 'Some intensives and laboratories run at the same time. Choose one of the parallel options.'], ['Attendance', 'Multi-day formats are booked as complete sequences.'], ['Registration', 'Advance registration and payment are preferred. On-the-door participation is possible only when places remain.'], ['Prices', 'All prices are in euros. Regular prices are available until 1 September 2026; Late prices apply after 1 September 2026.'], ['Individual support', 'If the standard price is a barrier, contact the festival team. Individual requests may be considered depending on availability.'], ['Cancellations', 'Cancellation and refund conditions will be shared before payment.']],
    },
    faqTitle: 'Questions',
    faq: [
      ['Can I attend only part of the festival?', 'Yes. Choose the Opening Weekend, a CI intensive, a Performance Lab, JAM Access or a Family & Youth format.'],
      ['Can I attend both parallel intensives or laboratories?', 'No. When formats run at the same time, choose one.'],
      ['Are JAMs included in CI and Performance Lab prices?', 'No. JAMs can be added through Participant JAM Add-on pricing.'],
      ['Can I pay for a JAM on the door?', 'Yes, when capacity remains. Advance registration and payment are preferred.'],
      ['Can another family member join?', 'Yes. One additional child or adult from the same family can join at the reduced additional-family rate.'],
      ['Do I need to reserve individual performances with a Full Festival Pass?', 'No. The festival reserves a dedicated seating section for Full Festival Pass holders.'],
      ['When is my registration confirmed?', 'After availability is confirmed and payment has been received.'],
    ],
    final: { title: 'Find your way into Contact+', text: 'Choose the full festival or build a focused path through practice, performance, JAMs and the Family & Youth Program.' },
  },
  ro: {
    title: 'Abonamente și participare',
    strapline: 'Mișcare · Improvizație de contact · Performance',
    lead: 'Alege cum vrei să participi la Contact+.',
    heroText: 'Alătură-te întregului festival de nouă zile, urmează un traseu concentrat de Improvizație de contact sau performance, începe cu weekendul de deschidere ori participă prin JAM-uri și Programul pentru familii și tineri.',
    date: '26 septembrie — 4 octombrie 2026', place: 'Chișinău, Moldova',
    actions: { register: 'Înscrie-te la Contact+', program: 'Explorează programul', schedule: 'Vezi orarul', soon: 'Disponibil în curând' },
    pricing: { regular: 'Regular', late: 'Late', regularNote: 'Până la 1 septembrie', lateNote: 'După 1 septembrie', intro: 'Prețurile Regular sunt valabile până la 1 septembrie 2026. După 1 septembrie 2026 se aplică prețurile Late.', label: 'Prețuri Regular și Late', currency: 'Toate prețurile sunt în euro' },
    how: {
      title: 'Cum funcționează participarea',
      paragraphs: ['Există mai multe feluri de a intra în Contact+.', 'Full Festival Pass oferă cel mai larg acces. Poți alege și un traseu concentrat prin weekendul de deschidere, Improvizație de contact, Performance Labs, JAM-uri sau Programul pentru familii și tineri.', 'Unele formate au loc în paralel. Când două intensive sau laboratoare se desfășoară în același timp, participanții aleg unul. Anumite formate suplimentare pot fi adăugate la un preț combinat redus.'],
      steps: ['Alege Full Festival Pass sau traseul principal.', 'Extinde-l cu un intensiv, laborator compatibil ori JAM-uri selectate.', 'Participă separat la formatele disponibile individual.', 'Cumpără bilete separate la performance-uri prin platforma festivalului, când se deschid vânzările.'],
    },
    full: {
      title: 'Full Festival Pass', kicker: 'Ritmul complet al festivalului',
      text: 'Pentru cei care vor să intre în ritmul complet Contact+. Abonamentul oferă acces la întregul program de practică, performance și viață comună a festivalului, în limitele orarului.',
      includesTitle: 'Inclus în Full Festival Pass',
      includes: ['Toate intensivele de Improvizație de contact', 'Toate Performance Labs', 'Toate JAM-urile', 'Prezentări și performance-uri', 'Întâlniri și evenimente comune ale festivalului', 'Formatele Programului pentru familii și tineri potrivite vârstei și cadrului de participare', 'Family Time & Discussion'],
      parallel: 'Unele evenimente au loc în paralel. În aceste cazuri, deținătorii Full Festival Pass aleg evenimentul la care participă.',
      performances: 'La fiecare performance este rezervată o zonă pentru deținătorii Full Festival Pass, astfel încât nu este necesară alegerea în avans a fiecărui spectacol.',
      family: 'Un deținător al abonamentului poate participa împreună cu copilul la un eveniment Family & Youth potrivit, fără un Family Pass separat. Datele copilului trebuie totuși incluse în formular, pentru capacitate și organizare.',
      noteLabels: ['Evenimente paralele', 'Performance-uri', 'Participarea familiei'],
      cta: 'Înscrie-te pentru Full Festival Pass',
    },
    paths: {
      title: 'Alege cum vrei să participi',
      text: 'Alege un traseu principal de participare. JAM-urile compatibile și formatele suplimentare pot fi adăugate la înscriere.',
      items: [
        ['full-festival', 'Full Festival Pass', '9 zile · €450 Regular', 'Pentru ritmul complet al festivalului'],
        ['opening', 'Weekend de deschidere', '2 zile · €120 Regular', 'Pentru o primă intrare clară în Contact+'],
        ['ci', 'Improvizație de contact', '3–5 zile · de la €100 Regular', 'Pentru o practică intensivă de mișcare'],
        ['labs', 'Performance Labs', '3–6 zile · de la €130 Regular', 'Pentru un proces concentrat de performance'],
        ['family', 'Program pentru familii și tineri', '1–2 zile · de la €40 Regular', 'Pentru copii, familii și tineri'],
        ['jams', 'Acces la JAM-uri', 'Date individuale · de la €10 Regular', 'Pentru participare flexibilă'],
      ],
    },
    opening: {
      title: 'Opening Weekend Pass', text: 'Începe Contact+ prin două zile legate de practică și evenimentele de deschidere.',
      choose: 'Alege exact unul dintre cele două formate paralele de două zile:', meta: 'Intensiv de 2 zile',
      after: 'Apoi participă la JAM-ul primelor întâlniri, Cercul de bun-venit și JAM și The Wild One. Participanții la weekendul de deschidere pot alege să vină la The Wild One.',
      unavailable: 'Shared Awareness și Arriving into the Touch sunt disponibile prin acest abonament și nu se vând separat în prezent.',
      cta: 'Alege formatul de deschidere',
      packageTitle: 'Opening Weekend Pass include',
      chooseTitle: 'Alege un intensiv',
      includedTitle: 'Inclus indiferent de alegere',
      includedText: 'Opening Weekend Pass include unul dintre cele două intensive paralele de mai sus și toate cele trei evenimente de mai jos.',
      selectionNote: 'Indică intensivul ales în formularul de înscriere.',
    },
    ci: {
      title: 'Improvizație de contact', intro: 'Alege un intensiv de Improvizație de contact de trei zile, continuă cu Risk, Play & Flight sau combină ambele etape într-un traseu mai lung de practică.',
      mainTitle: 'Intensiv principal de trei zile', choose: 'Alege unul dintre cele două formate paralele:', mainMeta: 'Intensiv de Improvizație de contact · 3 zile',
      secondTitle: 'Risk, Play & Flight', secondMeta: 'Intensiv de Improvizație de contact · 2 zile',
      secondText: 'Acest intensiv are loc separat. Poate fi cumpărat individual sau adăugat la oricare dintre intensivele principale.',
      separate: 'Preț separat', combined: 'Preț ca al doilea format de IC', discount: 'Prețul redus se aplică pentru Risk, Play & Flight ca al doilea format.',
      total: 'Total combinat', regularTotal: '€245 Regular', lateTotal: '€325 Late',
      excluded: 'Practicile de dimineață, discuțiile, alte evenimente comune și JAM-urile nu sunt incluse automat. JAM-urile pot fi adăugate separat.',
      ctas: ['Alege un intensiv de IC', 'Adaugă Risk, Play & Flight', 'Adaugă JAM-uri'],
      builderTitle: 'Alege una dintre cele trei forme de participare',
      builderText: 'Alege formatul potrivit pentru cantitatea de practică pe care o dorești.',
      optionTitles: ['Intensiv de 3 zile', 'Risk, Play & Flight', 'Ambele — traseu de 5 zile'],
      optionMeta: ['3 zile · alege un intensiv paralel', '2 zile · intensiv independent', '5 zile · intensiv principal + Risk, Play & Flight'],
      optionNotes: ['Alege CI as ArtSport sau Dynamic Flying.', 'Participă la Risk, Play & Flight fără un intensiv principal.', 'Alege un intensiv principal și continuă cu Risk, Play & Flight.'],
      register: 'Înscrie-te la Improvizație de contact',
      formNote: 'Vei indica opțiunea de participare și intensivul în formularul de înscriere.',
    },
    labs: {
      title: 'Performance Labs', intro: 'Alege un laborator de trei zile, adaugă Seeing and being seen sau urmează ambele etape ca traseu performativ mai lung.',
      mainTitle: 'Laborator principal', choose: 'Alege unul dintre cele două formate paralele de trei zile:', mainMeta: 'Laborator de performance · 3 zile',
      secondTitle: 'Seeing and being seen', secondMeta: 'Laborator de performance · 3 zile',
      secondText: 'Acest laborator are loc separat. Poate fi cumpărat individual sau adăugat la oricare dintre laboratoarele principale.',
      separate: 'Preț separat', combined: 'Preț ca al doilea laborator', discount: 'Prețul redus se aplică pentru Seeing and being seen ca al doilea laborator.',
      total: 'Total combinat', regularTotal: '€295 Regular', lateTotal: '€380 Late',
      note: 'Toate prezentările laboratoarelor sunt accesibile cu orice opțiune Performance Labs. Nu este necesară o scrisoare de motivație, selecție sau aprobarea profesorului. JAM-urile pot fi adăugate separat.',
      ctas: ['Alege un Performance Lab', 'Adaugă Seeing and being seen', 'Adaugă JAM-uri'],
      builderTitle: 'Alege una dintre cele trei forme de participare',
      builderText: 'Alege formatul potrivit pentru cantitatea de practică pe care o dorești.',
      optionTitles: ['Performance Lab de 3 zile', 'Seeing and being seen', 'Ambele — traseu de 6 zile'],
      optionMeta: ['3 zile · alege un laborator paralel', '3 zile · laborator independent', '6 zile · laborator principal + Seeing and being seen'],
      optionNotes: ['Alege Choice as Bodily Experience sau Touching Stories.', 'Participă la Seeing and being seen fără un laborator principal.', 'Alege un laborator principal și continuă cu Seeing and being seen.'],
      register: 'Înscrie-te la Performance Labs',
      formNote: 'Vei indica opțiunea de participare și laboratorul în formularul de înscriere.',
    },
    jams: {
      title: 'Acces la JAM-uri', intro: 'Alege JAM-uri individuale sau creează un traseu mai lung prin festival. În formular, indică JAM-urile la care intenționezi să participi.',
      events: ['JAM — 26 septembrie', 'JAM — 27 septembrie', 'JAM — 28 septembrie', 'JAM — 29 septembrie', 'JAM — 3 octombrie', 'JAM — 4 octombrie'],
      generalTitle: 'Prețuri doar pentru JAM-uri', generalNote: 'Pentru vizitatorii care nu cumpără un intensiv de IC sau un Performance Lab.',
      participantTitle: 'Prețuri add-on pentru participanți', participantNote: 'Pentru cei care cumpără un intensiv de IC sau un Performance Lab. Continuă practica în JAM-uri și rămâi conectat la ritmul comun al festivalului.',
      single: 'Un JAM', three: 'Trei sau mai multe', perJam: 'per JAM', one: '1 JAM', all: 'Toate cele 6 JAM-uri',
      capacity: 'Înregistrarea și plata în avans sunt preferate. Intrarea și plata la ușă sunt posibile doar dacă mai sunt locuri.',
      choiceTitle: 'Ce preț pentru JAM-uri ți se aplică?',
      generalChoice: 'Doar JAM-uri',
      participantChoice: 'Intensiv IC sau Performance Lab + JAM-uri',
    },
    family: {
      title: 'Program pentru familii și tineri', intro: 'Alege participarea în familie sau formatul complet Youth Dance Class de două zile.',
      passTitle: 'Family Pass', includedTitle: 'Formate incluse', includes: 'Un Family Pass include un copil și un adult însoțitor, o clasă Little Curiosity potrivită vârstei, The Wild One și Family Time & Discussion.',
      age: 'Alege Little Curiosity după vârsta copilului: sub 6 ani în ziua 1, 6+ în ziua 2. Adultul însoțitor participă la The Wild One.',
      additional: 'Copil sau adult suplimentar din aceeași familie', additionalText: 'Adaugă un copil sau un adult din aceeași familie la prețul redus de mai jos.',
      wild: 'The Wild One va fi vândut și separat ca bilet la performance.',
      youthTitle: 'Youth Dance Class', youthMeta: 'Format complet de 2 zile', youthText: 'Un format de mișcare de două zile creat în primul rând pentru adolescenți și tineri. Se vinde doar ca format complet de două zile.',
      productsTitle: 'Alege un produs de participare',
      additionalLabel: 'Opțiune suplimentară pentru Family Pass',
    },
    performances: { title: 'Performance-uri', text: 'Biletele la performance-uri vor fi disponibile separat prin platforma festivalului. Deținătorii Full Festival Pass au acces printr-o zonă rezervată. Opening Weekend Pass include The Wild One.', cta: 'Explorează biletele la performance-uri' },
    registration: {
      title: 'Cum funcționează înscrierea',
      steps: [['Alege traseul', 'Selectează Full Festival Pass, un traseu concentrat, participarea Family & Youth sau JAM-urile dorite.'], ['Completează formularul', 'Indică formatele și JAM-urile la care vrei să participi.'], ['Primește confirmarea', 'Echipa confirmă disponibilitatea și trimite instrucțiunile de plată.'], ['Finalizează plata', 'Locul este asigurat după confirmarea plății.'], ['Primește informațiile practice', 'Detaliile finale de organizare sunt trimise înainte de festival.']],
    },
    practical: {
      title: 'Condiții practice',
      groupTitles: ['Participare și capacitate', 'Înregistrare și prețuri', 'Sprijin individual', 'Anulări'],
      items: [['Capacitate', 'Locurile la intensive, laboratoare, JAM-uri și formatele Family & Youth pot fi limitate.'], ['Formate paralele', 'Unele intensive și laboratoare au loc simultan. Alege una dintre opțiunile paralele.'], ['Participare', 'Formatele de mai multe zile se rezervă ca secvențe complete.'], ['Înregistrare', 'Înregistrarea și plata în avans sunt preferate. Participarea la ușă este posibilă doar dacă mai sunt locuri.'], ['Prețuri', 'Toate prețurile sunt în euro. Regular este valabil până la 1 septembrie 2026; după această dată se aplică Late.'], ['Sprijin individual', 'Dacă prețul standard este o barieră, contactează echipa festivalului. Cererile individuale pot fi analizate în funcție de posibilități.'], ['Anulări', 'Condițiile de anulare și rambursare vor fi comunicate înainte de plată.']],
    },
    faqTitle: 'Întrebări',
    faq: [
      ['Pot participa doar la o parte din festival?', 'Da. Alege weekendul de deschidere, un intensiv de IC, un Performance Lab, acces la JAM-uri sau un format Family & Youth.'],
      ['Pot participa la ambele intensive sau laboratoare paralele?', 'Nu. Când formatele au loc simultan, alegi unul.'],
      ['JAM-urile sunt incluse în prețurile intensivului de IC sau Performance Lab?', 'Nu. Pot fi adăugate prin Participant JAM Add-on.'],
      ['Pot plăti la ușă pentru un JAM?', 'Da, dacă mai sunt locuri. Sunt preferate înregistrarea și plata în avans.'],
      ['Poate participa încă un membru al familiei?', 'Da. Un copil sau adult suplimentar din aceeași familie poate participa la prețul redus pentru familie.'],
      ['Trebuie să rezerv performance-uri individuale cu Full Festival Pass?', 'Nu. Festivalul rezervă o zonă dedicată deținătorilor Full Festival Pass.'],
      ['Când este confirmată înregistrarea?', 'După confirmarea disponibilității și primirea plății.'],
    ],
    final: { title: 'Găsește-ți drumul în Contact+', text: 'Alege întregul festival sau construiește un traseu concentrat prin practică, performance, JAM-uri și Programul pentru familii și tineri.' },
  },
  ru: {
    title: 'Абонементы и участие',
    strapline: 'Движение · Контактная импровизация · Перформанс',
    lead: 'Выберите, как вы хотите участвовать в Contact+.',
    heroText: 'Проведите на фестивале все девять дней, выберите отдельный путь в Контактной импровизации или перформансе, начните с открывающего уикенда либо присоединитесь к JAM-ам и программе для семей и молодёжи.',
    date: '26 сентября — 4 октября 2026', place: 'Кишинёв, Молдова',
    actions: { register: 'Зарегистрироваться на Contact+', program: 'Посмотреть программу', schedule: 'Открыть расписание', soon: 'Скоро' },
    pricing: { regular: 'Regular', late: 'Late', regularNote: 'До 1 сентября', lateNote: 'После 1 сентября', intro: 'Цены Regular действуют до 1 сентября 2026 года. После 1 сентября 2026 года применяются цены Late.', label: 'Цены Regular и Late', currency: 'Все цены указаны в евро' },
    how: {
      title: 'Как устроено участие',
      paragraphs: ['В Contact+ можно войти разными путями.', 'Full Festival Pass даёт самый широкий доступ. Можно также выбрать отдельный путь через открывающий уикенд, Контактную импровизацию, Performance Labs, JAM-ы или программу для семей и молодёжи.', 'Некоторые форматы идут параллельно. Если два интенсива или лаборатории проходят одновременно, участник выбирает один. Некоторые дополнительные форматы можно добавить по сниженной комбинированной цене.'],
      steps: ['Выберите Full Festival Pass или основной путь.', 'Дополните его совместимым интенсивом, лабораторией или выбранными JAM-ами.', 'Присоединяйтесь к отдельным форматам, где это возможно.', 'Покупайте отдельные билеты на перформансы через билетную платформу фестиваля после открытия продаж.'],
    },
    full: {
      title: 'Full Festival Pass', kicker: 'Полный ритм фестиваля',
      text: 'Для тех, кто хочет войти в полный ритм Contact+. Абонемент открывает всю программу практики, перформанса и общей фестивальной жизни в пределах возможностей расписания.',
      includesTitle: 'Входит в Full Festival Pass',
      includes: ['Все интенсивы по Контактной импровизации', 'Все Performance Labs', 'Все JAM-ы', 'Показы и перформансы', 'Встречи и общие события фестиваля', 'Форматы программы для семей и молодёжи при соответствии возрасту и условиям участия', 'Family Time & Discussion'],
      parallel: 'Некоторые события идут параллельно. В таких случаях владельцы Full Festival Pass выбирают, какое событие посетить.',
      performances: 'На каждой площадке для владельцев Full Festival Pass резервируется отдельная зона, поэтому выбирать перформансы заранее не нужно.',
      family: 'Владелец абонемента может посетить подходящее событие Family & Youth вместе с ребёнком без отдельного Family Pass. Информацию о ребёнке всё равно нужно указать при регистрации для учёта мест и организации.',
      noteLabels: ['Параллельные события', 'Перформансы', 'Семейное участие'],
      cta: 'Зарегистрироваться на Full Festival Pass',
    },
    paths: {
      title: 'Выберите, как хотите участвовать',
      text: 'Выберите один основной путь. Совместимые JAM-ы и дополнительные форматы можно добавить при регистрации.',
      items: [
        ['full-festival', 'Full Festival Pass', '9 дней · €450 Regular', 'Для полного ритма фестиваля'],
        ['opening', 'Открывающий уикенд', '2 дня · €120 Regular', 'Для понятного первого знакомства с Contact+'],
        ['ci', 'Контактная импровизация', '3–5 дней · от €100 Regular', 'Для интенсивной практики движения'],
        ['labs', 'Performance Labs', '3–6 дней · от €130 Regular', 'Для сфокусированного процесса в перформансе'],
        ['family', 'Программа для семей и молодёжи', '1–2 дня · от €40 Regular', 'Для детей, семей и молодых взрослых'],
        ['jams', 'Доступ к JAM-ам', 'Отдельные даты · от €10 Regular', 'Для гибкого участия'],
      ],
    },
    opening: {
      title: 'Opening Weekend Pass', text: 'Начните Contact+ с двух связанных дней практики и открывающих событий фестиваля.',
      choose: 'Выберите ровно один из двух параллельных двухдневных форматов:', meta: 'Интенсив · 2 дня',
      after: 'Затем присоединитесь к First Meetings JAM, Welcoming Open Circle & JAM и The Wild One. Участники открывающего уикенда могут выбрать посещение The Wild One.',
      unavailable: 'Shared Awareness и Arriving into the Touch доступны только в рамках этого абонемента и сейчас не продаются отдельно.',
      cta: 'Выбрать открывающий формат',
      packageTitle: 'В Opening Weekend Pass входит',
      chooseTitle: 'Выберите один интенсив',
      includedTitle: 'Входит при любом выборе',
      includedText: 'Opening Weekend Pass включает один из двух параллельных интенсивов выше и все три события ниже.',
      selectionNote: 'Укажите выбранный интенсив в регистрационной форме.',
    },
    ci: {
      title: 'Контактная импровизация', intro: 'Выберите трёхдневный интенсив по Контактной импровизации, продолжите путь с Risk, Play & Flight или объедините обе части в более длинную практику.',
      mainTitle: 'Основной трёхдневный интенсив', choose: 'Выберите один из двух параллельных форматов:', mainMeta: 'Интенсив по Контактной импровизации · 3 дня',
      secondTitle: 'Risk, Play & Flight', secondMeta: 'Интенсив по Контактной импровизации · 2 дня',
      secondText: 'Этот интенсив проходит отдельно. Его можно купить самостоятельно или добавить к любому основному интенсиву.',
      separate: 'Отдельная цена', combined: 'Цена как второго формата КИ', discount: 'Сниженная цена применяется к Risk, Play & Flight как ко второму формату.',
      total: 'Общая стоимость', regularTotal: '€245 Regular', lateTotal: '€325 Late',
      excluded: 'Утренние практики, обсуждения, другие общие события и JAM-ы не включены автоматически. JAM-ы можно добавить отдельно.',
      ctas: ['Выбрать интенсив КИ', 'Добавить Risk, Play & Flight', 'Добавить JAM-ы'],
      builderTitle: 'Выберите один из трёх способов участия',
      builderText: 'Выберите формат под желаемую продолжительность практики.',
      optionTitles: ['Интенсив на 3 дня', 'Risk, Play & Flight', 'Оба — путь на 5 дней'],
      optionMeta: ['3 дня · выберите один параллельный интенсив', '2 дня · самостоятельный интенсив', '5 дней · основной интенсив + Risk, Play & Flight'],
      optionNotes: ['Выберите CI as ArtSport или Dynamic Flying.', 'Посетите Risk, Play & Flight без основного интенсива.', 'Выберите основной интенсив и продолжите с Risk, Play & Flight.'],
      register: 'Зарегистрироваться на Контактную импровизацию',
      formNote: 'В регистрационной форме вы укажете вариант участия и выбранный интенсив.',
    },
    labs: {
      title: 'Performance Labs', intro: 'Выберите одну трёхдневную лабораторию, добавьте Seeing and being seen или пройдите обе части как более длинный путь в перформансе.',
      mainTitle: 'Основная лаборатория', choose: 'Выберите один из двух параллельных трёхдневных форматов:', mainMeta: 'Перформанс-лаборатория · 3 дня',
      secondTitle: 'Seeing and being seen', secondMeta: 'Перформанс-лаборатория · 3 дня',
      secondText: 'Эта лаборатория проходит отдельно. Её можно купить самостоятельно или добавить к любой основной лаборатории.',
      separate: 'Отдельная цена', combined: 'Цена как второй лаборатории', discount: 'Сниженная цена применяется к Seeing and being seen как ко второй лаборатории.',
      total: 'Общая стоимость', regularTotal: '€295 Regular', lateTotal: '€380 Late',
      note: 'Все связанные показы доступны с любым вариантом участия в Performance Labs. Мотивационное письмо, отбор и разрешение преподавателя сейчас не требуются. JAM-ы можно добавить отдельно.',
      ctas: ['Выбрать Performance Lab', 'Добавить Seeing and being seen', 'Добавить JAM-ы'],
      builderTitle: 'Выберите один из трёх способов участия',
      builderText: 'Выберите формат под желаемую продолжительность практики.',
      optionTitles: ['Performance Lab на 3 дня', 'Seeing and being seen', 'Обе — путь на 6 дней'],
      optionMeta: ['3 дня · выберите одну параллельную лабораторию', '3 дня · самостоятельная лаборатория', '6 дней · основная лаборатория + Seeing and being seen'],
      optionNotes: ['Выберите Choice as Bodily Experience или Touching Stories.', 'Посетите Seeing and being seen без основной лаборатории.', 'Выберите основную лабораторию и продолжите с Seeing and being seen.'],
      register: 'Зарегистрироваться на Performance Labs',
      formNote: 'В регистрационной форме вы укажете вариант участия и выбранную лабораторию.',
    },
    jams: {
      title: 'Доступ к JAM-ам', intro: 'Выберите отдельные JAM-ы или создайте более длинный путь через фестиваль. При регистрации укажите, какие JAM-ы планируете посетить.',
      events: ['JAM — 26 сентября', 'JAM — 27 сентября', 'JAM — 28 сентября', 'JAM — 29 сентября', 'JAM — 3 октября', 'JAM — 4 октября'],
      generalTitle: 'Цена при участии только в JAM-ах', generalNote: 'Для гостей, которые не покупают интенсив КИ или Performance Lab.',
      participantTitle: 'Дополнительная цена для участников', participantNote: 'Для участников интенсива КИ или Performance Lab. Продолжите практику в JAM-ах и оставайтесь в общем ритме фестиваля.',
      single: 'Один JAM', three: 'Три и более', perJam: 'за JAM', one: '1 JAM', all: 'Все 6 JAM-ов',
      capacity: 'Предпочтительны предварительная регистрация и оплата. Вход и оплата на месте возможны, только если остаются свободные места.',
      choiceTitle: 'Какая цена на JAM-ы относится к вам?',
      generalChoice: 'Только JAM-ы',
      participantChoice: 'Интенсив КИ или Performance Lab + JAM-ы',
    },
    family: {
      title: 'Программа для семей и молодёжи', intro: 'Выберите семейное участие или полный двухдневный формат Youth Dance Class.',
      passTitle: 'Family Pass', includedTitle: 'Включённые форматы', includes: 'Один Family Pass включает одного ребёнка и одного сопровождающего взрослого, подходящий по возрасту класс Little Curiosity, The Wild One и Family Time & Discussion.',
      age: 'Выберите Little Curiosity по возрасту ребёнка: до 6 лет в день 1, 6+ в день 2. Сопровождающий взрослый участвует в The Wild One.',
      additional: 'Дополнительный ребёнок или взрослый из той же семьи', additionalText: 'Добавьте одного ребёнка или взрослого из той же семьи по сниженной цене ниже.',
      wild: 'The Wild One будет также продаваться отдельно как билет на перформанс.',
      youthTitle: 'Youth Dance Class', youthMeta: 'Полный формат · 2 дня', youthText: 'Двухдневный формат движения, созданный прежде всего для подростков и молодых взрослых. Продаётся только как полный двухдневный формат.',
      productsTitle: 'Выберите один формат участия',
      additionalLabel: 'Дополнительная опция Family Pass',
    },
    performances: { title: 'Перформансы', text: 'Билеты на перформансы будут доступны отдельно на билетной платформе фестиваля. Владельцы Full Festival Pass проходят в зарезервированную фестивальную зону. Opening Weekend Pass включает The Wild One.', cta: 'Посмотреть билеты на перформансы' },
    registration: {
      title: 'Как проходит регистрация',
      steps: [['Выберите путь', 'Выберите Full Festival Pass, отдельный программный путь, Family & Youth или нужные JAM-ы.'], ['Заполните форму', 'Укажите форматы и JAM-ы, которые хотите посетить.'], ['Получите подтверждение', 'Команда подтверждает наличие мест и отправляет инструкции по оплате.'], ['Завершите оплату', 'Место закрепляется после подтверждения оплаты.'], ['Получите практическую информацию', 'Финальные организационные детали придут до фестиваля.']],
    },
    practical: {
      title: 'Практические условия',
      groupTitles: ['Участие и количество мест', 'Регистрация и цены', 'Индивидуальная поддержка', 'Отмена'],
      items: [['Количество мест', 'Места на интенсивах, в лабораториях, JAM-ах и форматах Family & Youth могут быть ограничены.'], ['Параллельные форматы', 'Некоторые интенсивы и лаборатории идут одновременно. Выберите один из параллельных вариантов.'], ['Посещение', 'Многодневные форматы бронируются целиком.'], ['Регистрация', 'Предпочтительны предварительная регистрация и оплата. Участие с оплатой на месте возможно, только если остаются места.'], ['Цены', 'Все цены указаны в евро. Regular действует до 1 сентября 2026 года; затем применяется Late.'], ['Индивидуальная поддержка', 'Если стандартная цена становится препятствием, напишите команде фестиваля. Индивидуальные запросы могут быть рассмотрены в зависимости от возможностей.'], ['Отмена', 'Условия отмены и возврата сообщат до оплаты.']],
    },
    faqTitle: 'Вопросы',
    faq: [
      ['Можно посетить только часть фестиваля?', 'Да. Выберите открывающий уикенд, интенсив КИ, Performance Lab, JAM-ы или формат Family & Youth.'],
      ['Можно посетить оба параллельных интенсива или лаборатории?', 'Нет. Когда форматы идут одновременно, нужно выбрать один.'],
      ['JAM-ы включены в цены интенсива КИ или Performance Lab?', 'Нет. Их можно добавить по цене Participant JAM Add-on.'],
      ['Можно оплатить JAM на месте?', 'Да, если остаются места. Предпочтительны предварительная регистрация и оплата.'],
      ['Может присоединиться ещё один член семьи?', 'Да. Один дополнительный ребёнок или взрослый из той же семьи может присоединиться по сниженной семейной цене.'],
      ['Нужно бронировать отдельные перформансы с Full Festival Pass?', 'Нет. Фестиваль резервирует отдельную зону для владельцев Full Festival Pass.'],
      ['Когда регистрация подтверждена?', 'После подтверждения наличия места и получения оплаты.'],
    ],
    final: { title: 'Найдите свой путь в Contact+', text: 'Выберите весь фестиваль или соберите отдельный путь через практику, перформанс, JAM-ы и программу для семей и молодёжи.' },
  },
};
