[build]
  command = "pnpm run build"
  publish = "dist"

[[redirects]]
  from = "/program"
  to = "/en/program"
  status = 302

[[redirects]]
  from = "/schedule"
  to = "/en/schedule"
  status = 302

[[redirects]]
  from = "/artists"
  to = "/en/artists"
  status = 302
